#This is the workflow name
name: CICD

#This is the manual click (delivery) workflow execute whenever user wants 
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: This is the environemnt value where this workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - stg


jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "Code clone from GitHub"
  build: 
     needs: [code]
     runs-on: ubuntu-latest
     steps:
      - name: Build docker container
        run: echo "Docker container build"
  test:
    needs: [code, build]
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
        run: echo "Testing the container"
  deploy:
    if: inputs.environment == 'dev' 
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "Docker compose deployed the app"
